language: java

before_install:
 - uname -a
 - echo -e "Package: *\nPin: release a=precise*\nPin-Priority: 2012" >> /etc/apt/preferences
 - sudo apt-get dist-upgrade -qq
 - sudo apt-get install -y ia32-libs-multiarch
